/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.MainDAO;
import Model.ChuyenBay;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TuanDuc
 */
public class frmMain extends javax.swing.JFrame {

    int showHideMenu = 1;
    int showHideSubMenu_ThanhToan = 1;
    int showHideSubMenu_Ve = 1;
    int showHideSubMenu_ChuyenBay = 1;
    String chucVu = "";

    void checkUser() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        chucVu = frmLogin.vt;
                        String ten = new MainDAO().getHoTen(frmLogin.tenDN);
                        if (ten.isEmpty()) {
                            lblUser.setText("NULL");
                        } else {
                            lblUser.setText(ten);
                            lblChucVu.setText(frmLogin.vt);
                        }
                        Thread.sleep(100);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }.start();
    }

    void close() {
        System.exit(0);
    }

    void minus() {
        this.setState(1);
    }

    void loadOpenForm() {
        for (double i = 0.0; i < 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.parseFloat(val);
            this.setOpacity(f);
            try {
                Thread.sleep(70);
            } catch (Exception e) {
            }
        }
    }

    void hover(int so, JPanel pnl) {
        if (so == 1) {
            pnl.setBackground(new Color(122, 89, 186));
            pnl.setCursor(new Cursor(HAND_CURSOR));
        } else {
            pnl.setBackground(new Color(102, 153, 255));
        }
    }

    void changeIcon(int so, JButton btn, String url) {
        if (so == 1) {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
            btn.setCursor(new Cursor(HAND_CURSOR));
        } else {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
        }
    }

    void menu() {
        showHideMenu++;
        if (showHideMenu % 2 == 0) {
            pnlNavigation.setBackground(new Color(55, 38, 91));
            pnlMenu.setSize(60, 800);
            btnMenu.setLocation(80, 20);
            lblSlogan.setLocation(130, 23);
        } else {
            pnlNavigation.setBackground(new Color(83, 62, 128));
            pnlMenu.setSize(230, 800);
            btnMenu.setLocation(250, 20);
            lblSlogan.setLocation(300, 23);
        }
    }

    void showHideSubMenu(int so, JPanel panel) {
        so++;
        if (so % 2 == 0) {
            pnlSubMenu.setVisible(true);
        } else {
            pnlSubMenu.setVisible(false);
        }
        JPanel[] pnl = new JPanel[]{pnlSubThanhToan, pnlSubVe, pnlSubChuyenBay};
        for (int i = 0; i < pnl.length; i++) {
            pnl[i].setVisible(false);
        }
        panel.setVisible(true);
    }

    void login() {
        new frmLogin().setVisible(true);
    }

    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        checkUser();
        pnlSubMenu.setVisible(false);
        tbpForm.setBackground(new Color(0, 0, 0, 0));
        tbpForm.removeAll();
        frmTrangChu tc = new frmTrangChu();
        tbpForm.addTab("", null, tc.getContentPane().getComponentAt(0, 0), null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblChucVu = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlTrangChu = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        pnlKhachHang = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        pnlNhanVien = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        pnlThanhToan = new javax.swing.JPanel();
        btnThanhtoan = new javax.swing.JButton();
        pnlQuanLyVe = new javax.swing.JPanel();
        btnQuanLyVe = new javax.swing.JButton();
        pnlQuanLyChuyenBay = new javax.swing.JPanel();
        btnQuanLyChuyenBay = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        pnlQuanLyDoanhThu = new javax.swing.JPanel();
        btnDoanhThuTheoQuy = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblSlogan = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnlSubMenu = new javax.swing.JPanel();
        pnlSubVe = new javax.swing.JPanel();
        pnlSubVe_VeMB = new javax.swing.JPanel();
        btnVeMayBay = new javax.swing.JButton();
        pnlSubVe_HangVe = new javax.swing.JPanel();
        btnHangVe = new javax.swing.JButton();
        pnlSubVe_LoaiVe = new javax.swing.JPanel();
        btnLoaiVe = new javax.swing.JButton();
        pnlSubVe_DichVu = new javax.swing.JPanel();
        btnDichVu = new javax.swing.JButton();
        pnlSubChuyenBay = new javax.swing.JPanel();
        pnlSubChuyenBay_ChuyenBay = new javax.swing.JPanel();
        btnChuyenBay = new javax.swing.JButton();
        pnlSubChuyenBay_TuyenBay = new javax.swing.JPanel();
        btnTuyenBay = new javax.swing.JButton();
        pnlSubChuyenBay_SanBay = new javax.swing.JPanel();
        btnSanBay = new javax.swing.JButton();
        pnlSubChuyenBay_MayBay = new javax.swing.JPanel();
        btnMayBay = new javax.swing.JButton();
        pnlSubChuyenBay_HangMayBay = new javax.swing.JPanel();
        btnHangMayBay = new javax.swing.JButton();
        pnlSubThanhToan = new javax.swing.JPanel();
        pnlSubThanhToan_HD = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        pnlSubThanhToan_HDCT = new javax.swing.JPanel();
        btnHDCT = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        tbpForm = new javax.swing.JTabbedPane();
        pnlFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(102, 153, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChucVu.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlMenu.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 20));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        lblUser.setText("Ngô Tuấn Đức");
        pnlMenu.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        pnlTrangChu.setBackground(new java.awt.Color(102, 153, 255));

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        btnTrangChu.setBorder(null);
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setContentAreaFilled(false);
        btnTrangChu.setDefaultCapable(false);
        btnTrangChu.setFocusPainted(false);
        btnTrangChu.setFocusable(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.setIconTextGap(25);
        btnTrangChu.setLabel("Trang chủ");
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangChuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 230, -1));

        pnlKhachHang.setBackground(new java.awt.Color(102, 153, 255));

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khachHang.png"))); // NOI18N
        btnKhachHang.setText("Quản lý hành khách");
        btnKhachHang.setBorder(null);
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setContentAreaFilled(false);
        btnKhachHang.setDefaultCapable(false);
        btnKhachHang.setFocusPainted(false);
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setIconTextGap(25);
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseExited(evt);
            }
        });
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 230, -1));

        pnlNhanVien.setBackground(new java.awt.Color(102, 153, 255));

        btnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/officer.png"))); // NOI18N
        btnNhanVien.setText("Quản lý nhân sự");
        btnNhanVien.setBorder(null);
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setDefaultCapable(false);
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.setIconTextGap(25);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, -1, -1));

        pnlThanhToan.setBackground(new java.awt.Color(102, 153, 255));

        btnThanhtoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money.png"))); // NOI18N
        btnThanhtoan.setText("Thanh toán");
        btnThanhtoan.setBorder(null);
        btnThanhtoan.setBorderPainted(false);
        btnThanhtoan.setContentAreaFilled(false);
        btnThanhtoan.setDefaultCapable(false);
        btnThanhtoan.setFocusPainted(false);
        btnThanhtoan.setFocusable(false);
        btnThanhtoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThanhtoan.setIconTextGap(25);
        btnThanhtoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThanhtoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThanhtoanMouseExited(evt);
            }
        });
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThanhToanLayout = new javax.swing.GroupLayout(pnlThanhToan);
        pnlThanhToan.setLayout(pnlThanhToanLayout);
        pnlThanhToanLayout.setHorizontalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlThanhToanLayout.setVerticalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, -1));

        pnlQuanLyVe.setBackground(new java.awt.Color(102, 153, 255));

        btnQuanLyVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuanLyVe.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ticket.png"))); // NOI18N
        btnQuanLyVe.setText("Quản lý vé");
        btnQuanLyVe.setBorder(null);
        btnQuanLyVe.setBorderPainted(false);
        btnQuanLyVe.setContentAreaFilled(false);
        btnQuanLyVe.setDefaultCapable(false);
        btnQuanLyVe.setFocusPainted(false);
        btnQuanLyVe.setFocusable(false);
        btnQuanLyVe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyVe.setIconTextGap(25);
        btnQuanLyVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyVeMouseExited(evt);
            }
        });
        btnQuanLyVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyVeLayout = new javax.swing.GroupLayout(pnlQuanLyVe);
        pnlQuanLyVe.setLayout(pnlQuanLyVeLayout);
        pnlQuanLyVeLayout.setHorizontalGroup(
            pnlQuanLyVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyVeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuanLyVe, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuanLyVeLayout.setVerticalGroup(
            pnlQuanLyVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuanLyVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLyVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 230, -1));

        pnlQuanLyChuyenBay.setBackground(new java.awt.Color(102, 153, 255));

        btnQuanLyChuyenBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuanLyChuyenBay.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyChuyenBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/clock.png"))); // NOI18N
        btnQuanLyChuyenBay.setText("Quản lý chuyến bay");
        btnQuanLyChuyenBay.setBorder(null);
        btnQuanLyChuyenBay.setBorderPainted(false);
        btnQuanLyChuyenBay.setContentAreaFilled(false);
        btnQuanLyChuyenBay.setDefaultCapable(false);
        btnQuanLyChuyenBay.setFocusPainted(false);
        btnQuanLyChuyenBay.setFocusable(false);
        btnQuanLyChuyenBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyChuyenBay.setIconTextGap(25);
        btnQuanLyChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyChuyenBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyChuyenBayMouseExited(evt);
            }
        });
        btnQuanLyChuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyChuyenBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyChuyenBayLayout = new javax.swing.GroupLayout(pnlQuanLyChuyenBay);
        pnlQuanLyChuyenBay.setLayout(pnlQuanLyChuyenBayLayout);
        pnlQuanLyChuyenBayLayout.setHorizontalGroup(
            pnlQuanLyChuyenBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyChuyenBayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuanLyChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuanLyChuyenBayLayout.setVerticalGroup(
            pnlQuanLyChuyenBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuanLyChuyenBay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLyChuyenBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 478, 230, -1));

        pnlNavigation.setBackground(new java.awt.Color(102, 153, 255));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setDefaultCapable(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setting.png"))); // NOI18N
        btnSetting.setBorder(null);
        btnSetting.setBorderPainted(false);
        btnSetting.setContentAreaFilled(false);
        btnSetting.setDefaultCapable(false);
        btnSetting.setFocusPainted(false);
        btnSetting.setFocusable(false);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
        });
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/group.png"))); // NOI18N
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.setContentAreaFilled(false);
        btnAccount.setDefaultCapable(false);
        btnAccount.setFocusPainted(false);
        btnAccount.setFocusable(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccountMouseExited(evt);
            }
        });
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSetting)
                .addGap(18, 18, 18)
                .addComponent(btnAccount)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccount)
                    .addComponent(btnSetting)
                    .addComponent(btnLogout))
                .addContainerGap())
        );

        pnlMenu.add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 758, 230, -1));

        pnlQuanLyDoanhThu.setBackground(new java.awt.Color(102, 153, 255));

        btnDoanhThuTheoQuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoanhThuTheoQuy.setForeground(new java.awt.Color(255, 255, 255));
        btnDoanhThuTheoQuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plan.png"))); // NOI18N
        btnDoanhThuTheoQuy.setText("Doanh thu quý ");
        btnDoanhThuTheoQuy.setBorder(null);
        btnDoanhThuTheoQuy.setBorderPainted(false);
        btnDoanhThuTheoQuy.setContentAreaFilled(false);
        btnDoanhThuTheoQuy.setFocusPainted(false);
        btnDoanhThuTheoQuy.setFocusable(false);
        btnDoanhThuTheoQuy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoanhThuTheoQuy.setIconTextGap(25);
        btnDoanhThuTheoQuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoanhThuTheoQuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoanhThuTheoQuyMouseExited(evt);
            }
        });
        btnDoanhThuTheoQuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuTheoQuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyDoanhThuLayout = new javax.swing.GroupLayout(pnlQuanLyDoanhThu);
        pnlQuanLyDoanhThu.setLayout(pnlQuanLyDoanhThuLayout);
        pnlQuanLyDoanhThuLayout.setHorizontalGroup(
            pnlQuanLyDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyDoanhThuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoanhThuTheoQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuanLyDoanhThuLayout.setVerticalGroup(
            pnlQuanLyDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDoanhThuTheoQuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLyDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 531, 230, -1));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 800));

        pnlHeader.setBackground(new java.awt.Color(235, 235, 235));
        pnlHeader.setMinimumSize(new java.awt.Dimension(990, 70));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1090, 70));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSlogan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(102, 153, 255));
        lblSlogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plane3.png"))); // NOI18N
        lblSlogan.setText("HỆ THỐNG BÁN VÉ MÁY BAY");
        lblSlogan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblSlogan.setIconTextGap(8);
        pnlHeader.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/closeMain.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlHeader.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minusMain.png"))); // NOI18N
        btnMinus.setBorder(null);
        btnMinus.setBorderPainted(false);
        btnMinus.setContentAreaFilled(false);
        btnMinus.setDefaultCapable(false);
        btnMinus.setFocusPainted(false);
        btnMinus.setFocusable(false);
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinusMouseExited(evt);
            }
        });
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        pnlHeader.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setDefaultCapable(false);
        btnMenu.setFocusPainted(false);
        btnMenu.setFocusable(false);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        pnlSubMenu.setLayout(new java.awt.CardLayout());

        pnlSubVe.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubVeMouseExited(evt);
            }
        });
        pnlSubVe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSubVe_VeMB.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubVe_VeMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubVe_VeMBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubVe_VeMBMouseExited(evt);
            }
        });

        btnVeMayBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVeMayBay.setForeground(new java.awt.Color(255, 255, 255));
        btnVeMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/airportVe.png"))); // NOI18N
        btnVeMayBay.setText("Vé máy bay");
        btnVeMayBay.setBorder(null);
        btnVeMayBay.setBorderPainted(false);
        btnVeMayBay.setContentAreaFilled(false);
        btnVeMayBay.setDefaultCapable(false);
        btnVeMayBay.setFocusPainted(false);
        btnVeMayBay.setFocusable(false);
        btnVeMayBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVeMayBay.setIconTextGap(13);
        btnVeMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeMayBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeMayBayMouseExited(evt);
            }
        });
        btnVeMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeMayBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubVe_VeMBLayout = new javax.swing.GroupLayout(pnlSubVe_VeMB);
        pnlSubVe_VeMB.setLayout(pnlSubVe_VeMBLayout);
        pnlSubVe_VeMBLayout.setHorizontalGroup(
            pnlSubVe_VeMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubVe_VeMBLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnlSubVe_VeMBLayout.setVerticalGroup(
            pnlSubVe_VeMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubVe_VeMBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVeMayBay)
                .addContainerGap())
        );

        pnlSubVe.add(pnlSubVe_VeMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 200, -1));

        pnlSubVe_HangVe.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubVe_HangVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubVe_HangVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubVe_HangVeMouseExited(evt);
            }
        });

        btnHangVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHangVe.setForeground(new java.awt.Color(255, 255, 255));
        btnHangVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/star.png"))); // NOI18N
        btnHangVe.setText("Hạng vé");
        btnHangVe.setBorder(null);
        btnHangVe.setBorderPainted(false);
        btnHangVe.setContentAreaFilled(false);
        btnHangVe.setDefaultCapable(false);
        btnHangVe.setFocusPainted(false);
        btnHangVe.setFocusable(false);
        btnHangVe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHangVe.setIconTextGap(13);
        btnHangVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHangVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHangVeMouseExited(evt);
            }
        });
        btnHangVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubVe_HangVeLayout = new javax.swing.GroupLayout(pnlSubVe_HangVe);
        pnlSubVe_HangVe.setLayout(pnlSubVe_HangVeLayout);
        pnlSubVe_HangVeLayout.setHorizontalGroup(
            pnlSubVe_HangVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubVe_HangVeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnHangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlSubVe_HangVeLayout.setVerticalGroup(
            pnlSubVe_HangVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubVe_HangVeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHangVe)
                .addContainerGap())
        );

        pnlSubVe.add(pnlSubVe_HangVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        pnlSubVe_LoaiVe.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubVe_LoaiVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubVe_LoaiVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubVe_LoaiVeMouseExited(evt);
            }
        });

        btnLoaiVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoaiVe.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ticketLVe.png"))); // NOI18N
        btnLoaiVe.setText("Loại vé");
        btnLoaiVe.setToolTipText("");
        btnLoaiVe.setBorder(null);
        btnLoaiVe.setBorderPainted(false);
        btnLoaiVe.setContentAreaFilled(false);
        btnLoaiVe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoaiVe.setDefaultCapable(false);
        btnLoaiVe.setFocusPainted(false);
        btnLoaiVe.setFocusable(false);
        btnLoaiVe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoaiVe.setIconTextGap(13);
        btnLoaiVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoaiVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoaiVeMouseExited(evt);
            }
        });
        btnLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubVe_LoaiVeLayout = new javax.swing.GroupLayout(pnlSubVe_LoaiVe);
        pnlSubVe_LoaiVe.setLayout(pnlSubVe_LoaiVeLayout);
        pnlSubVe_LoaiVeLayout.setHorizontalGroup(
            pnlSubVe_LoaiVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubVe_LoaiVeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlSubVe_LoaiVeLayout.setVerticalGroup(
            pnlSubVe_LoaiVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubVe_LoaiVeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoaiVe)
                .addContainerGap())
        );

        pnlSubVe.add(pnlSubVe_LoaiVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, -1));

        pnlSubVe_DichVu.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubVe_DichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubVe_DichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubVe_DichVuMouseExited(evt);
            }
        });

        btnDichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDichVu.setForeground(new java.awt.Color(255, 255, 255));
        btnDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/service.png"))); // NOI18N
        btnDichVu.setText("Dịch vụ");
        btnDichVu.setBorder(null);
        btnDichVu.setBorderPainted(false);
        btnDichVu.setContentAreaFilled(false);
        btnDichVu.setDefaultCapable(false);
        btnDichVu.setFocusPainted(false);
        btnDichVu.setFocusable(false);
        btnDichVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDichVu.setIconTextGap(13);
        btnDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDichVuMouseExited(evt);
            }
        });
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubVe_DichVuLayout = new javax.swing.GroupLayout(pnlSubVe_DichVu);
        pnlSubVe_DichVu.setLayout(pnlSubVe_DichVuLayout);
        pnlSubVe_DichVuLayout.setHorizontalGroup(
            pnlSubVe_DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubVe_DichVuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlSubVe_DichVuLayout.setVerticalGroup(
            pnlSubVe_DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubVe_DichVuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDichVu)
                .addContainerGap())
        );

        pnlSubVe.add(pnlSubVe_DichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, -1));

        pnlSubMenu.add(pnlSubVe, "card3");

        pnlSubChuyenBay.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBayMouseExited(evt);
            }
        });
        pnlSubChuyenBay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSubChuyenBay_ChuyenBay.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubChuyenBay_ChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_ChuyenBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_ChuyenBayMouseExited(evt);
            }
        });

        btnChuyenBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChuyenBay.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/road.png"))); // NOI18N
        btnChuyenBay.setText("Chuyến bay");
        btnChuyenBay.setActionCommand("btnChuyenBay");
        btnChuyenBay.setBorder(null);
        btnChuyenBay.setBorderPainted(false);
        btnChuyenBay.setContentAreaFilled(false);
        btnChuyenBay.setDefaultCapable(false);
        btnChuyenBay.setFocusPainted(false);
        btnChuyenBay.setFocusable(false);
        btnChuyenBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChuyenBay.setIconTextGap(13);
        btnChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChuyenBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChuyenBayMouseExited(evt);
            }
        });
        btnChuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubChuyenBay_ChuyenBayLayout = new javax.swing.GroupLayout(pnlSubChuyenBay_ChuyenBay);
        pnlSubChuyenBay_ChuyenBay.setLayout(pnlSubChuyenBay_ChuyenBayLayout);
        pnlSubChuyenBay_ChuyenBayLayout.setHorizontalGroup(
            pnlSubChuyenBay_ChuyenBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_ChuyenBayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlSubChuyenBay_ChuyenBayLayout.setVerticalGroup(
            pnlSubChuyenBay_ChuyenBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubChuyenBay_ChuyenBayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChuyenBay)
                .addContainerGap())
        );

        pnlSubChuyenBay.add(pnlSubChuyenBay_ChuyenBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        pnlSubChuyenBay_TuyenBay.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubChuyenBay_TuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_TuyenBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_TuyenBayMouseExited(evt);
            }
        });

        btnTuyenBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTuyenBay.setForeground(new java.awt.Color(255, 255, 255));
        btnTuyenBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/steet.png"))); // NOI18N
        btnTuyenBay.setText("Tuyến bay");
        btnTuyenBay.setBorder(null);
        btnTuyenBay.setBorderPainted(false);
        btnTuyenBay.setContentAreaFilled(false);
        btnTuyenBay.setDefaultCapable(false);
        btnTuyenBay.setFocusPainted(false);
        btnTuyenBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTuyenBay.setIconTextGap(13);
        btnTuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTuyenBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTuyenBayMouseExited(evt);
            }
        });
        btnTuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuyenBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubChuyenBay_TuyenBayLayout = new javax.swing.GroupLayout(pnlSubChuyenBay_TuyenBay);
        pnlSubChuyenBay_TuyenBay.setLayout(pnlSubChuyenBay_TuyenBayLayout);
        pnlSubChuyenBay_TuyenBayLayout.setHorizontalGroup(
            pnlSubChuyenBay_TuyenBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_TuyenBayLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnTuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlSubChuyenBay_TuyenBayLayout.setVerticalGroup(
            pnlSubChuyenBay_TuyenBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_TuyenBayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTuyenBay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubChuyenBay.add(pnlSubChuyenBay_TuyenBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        pnlSubChuyenBay_SanBay.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubChuyenBay_SanBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_SanBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_SanBayMouseExited(evt);
            }
        });

        btnSanBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSanBay.setForeground(new java.awt.Color(255, 255, 255));
        btnSanBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/location.png"))); // NOI18N
        btnSanBay.setText("Sân bay");
        btnSanBay.setBorder(null);
        btnSanBay.setBorderPainted(false);
        btnSanBay.setContentAreaFilled(false);
        btnSanBay.setDefaultCapable(false);
        btnSanBay.setFocusPainted(false);
        btnSanBay.setFocusable(false);
        btnSanBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanBay.setIconTextGap(13);
        btnSanBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSanBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSanBayMouseExited(evt);
            }
        });
        btnSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubChuyenBay_SanBayLayout = new javax.swing.GroupLayout(pnlSubChuyenBay_SanBay);
        pnlSubChuyenBay_SanBay.setLayout(pnlSubChuyenBay_SanBayLayout);
        pnlSubChuyenBay_SanBayLayout.setHorizontalGroup(
            pnlSubChuyenBay_SanBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_SanBayLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlSubChuyenBay_SanBayLayout.setVerticalGroup(
            pnlSubChuyenBay_SanBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_SanBayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSanBay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubChuyenBay.add(pnlSubChuyenBay_SanBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, -1));

        pnlSubChuyenBay_MayBay.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubChuyenBay_MayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_MayBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_MayBayMouseExited(evt);
            }
        });

        btnMayBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMayBay.setForeground(new java.awt.Color(255, 255, 255));
        btnMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/airportVe.png"))); // NOI18N
        btnMayBay.setText("Máy bay");
        btnMayBay.setBorder(null);
        btnMayBay.setBorderPainted(false);
        btnMayBay.setContentAreaFilled(false);
        btnMayBay.setDefaultCapable(false);
        btnMayBay.setFocusPainted(false);
        btnMayBay.setFocusable(false);
        btnMayBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMayBay.setIconTextGap(13);
        btnMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMayBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMayBayMouseExited(evt);
            }
        });
        btnMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubChuyenBay_MayBayLayout = new javax.swing.GroupLayout(pnlSubChuyenBay_MayBay);
        pnlSubChuyenBay_MayBay.setLayout(pnlSubChuyenBay_MayBayLayout);
        pnlSubChuyenBay_MayBayLayout.setHorizontalGroup(
            pnlSubChuyenBay_MayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_MayBayLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlSubChuyenBay_MayBayLayout.setVerticalGroup(
            pnlSubChuyenBay_MayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_MayBayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMayBay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubChuyenBay.add(pnlSubChuyenBay_MayBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, -1));

        pnlSubChuyenBay_HangMayBay.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubChuyenBay_HangMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_HangMayBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubChuyenBay_HangMayBayMouseExited(evt);
            }
        });

        btnHangMayBay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHangMayBay.setForeground(new java.awt.Color(255, 255, 255));
        btnHangMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/airplane.png"))); // NOI18N
        btnHangMayBay.setText("Hãng máy bay");
        btnHangMayBay.setBorder(null);
        btnHangMayBay.setBorderPainted(false);
        btnHangMayBay.setContentAreaFilled(false);
        btnHangMayBay.setDefaultCapable(false);
        btnHangMayBay.setFocusPainted(false);
        btnHangMayBay.setFocusable(false);
        btnHangMayBay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHangMayBay.setIconTextGap(13);
        btnHangMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHangMayBayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHangMayBayMouseExited(evt);
            }
        });
        btnHangMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangMayBayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubChuyenBay_HangMayBayLayout = new javax.swing.GroupLayout(pnlSubChuyenBay_HangMayBay);
        pnlSubChuyenBay_HangMayBay.setLayout(pnlSubChuyenBay_HangMayBayLayout);
        pnlSubChuyenBay_HangMayBayLayout.setHorizontalGroup(
            pnlSubChuyenBay_HangMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubChuyenBay_HangMayBayLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnHangMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlSubChuyenBay_HangMayBayLayout.setVerticalGroup(
            pnlSubChuyenBay_HangMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubChuyenBay_HangMayBayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHangMayBay)
                .addContainerGap())
        );

        pnlSubChuyenBay.add(pnlSubChuyenBay_HangMayBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        pnlSubMenu.add(pnlSubChuyenBay, "card4");

        pnlSubThanhToan.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubThanhToanMouseExited(evt);
            }
        });
        pnlSubThanhToan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSubThanhToan_HD.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubThanhToan_HD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDMouseExited(evt);
            }
        });

        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bill.png"))); // NOI18N
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setBorder(null);
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setContentAreaFilled(false);
        btnHoaDon.setDefaultCapable(false);
        btnHoaDon.setFocusPainted(false);
        btnHoaDon.setFocusable(false);
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon.setIconTextGap(13);
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseExited(evt);
            }
        });
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubThanhToan_HDLayout = new javax.swing.GroupLayout(pnlSubThanhToan_HD);
        pnlSubThanhToan_HD.setLayout(pnlSubThanhToan_HDLayout);
        pnlSubThanhToan_HDLayout.setHorizontalGroup(
            pnlSubThanhToan_HDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubThanhToan_HDLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSubThanhToan_HDLayout.setVerticalGroup(
            pnlSubThanhToan_HDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubThanhToan_HDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubThanhToan.add(pnlSubThanhToan_HD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 190, -1));
        pnlSubThanhToan_HD.getAccessibleContext().setAccessibleParent(pnlSubMenu);

        pnlSubThanhToan_HDCT.setBackground(new java.awt.Color(102, 153, 255));
        pnlSubThanhToan_HDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDCTMouseExited(evt);
            }
        });

        btnHDCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHDCT.setForeground(new java.awt.Color(255, 255, 255));
        btnHDCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/billDetail.png"))); // NOI18N
        btnHDCT.setText("Hóa đơn chi tiết");
        btnHDCT.setActionCommand("btnHoaDonChiTiet");
        btnHDCT.setBorder(null);
        btnHDCT.setBorderPainted(false);
        btnHDCT.setContentAreaFilled(false);
        btnHDCT.setDefaultCapable(false);
        btnHDCT.setFocusPainted(false);
        btnHDCT.setFocusable(false);
        btnHDCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHDCT.setIconTextGap(13);
        btnHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHDCTMouseExited(evt);
            }
        });
        btnHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubThanhToan_HDCTLayout = new javax.swing.GroupLayout(pnlSubThanhToan_HDCT);
        pnlSubThanhToan_HDCT.setLayout(pnlSubThanhToan_HDCTLayout);
        pnlSubThanhToan_HDCTLayout.setHorizontalGroup(
            pnlSubThanhToan_HDCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubThanhToan_HDCTLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSubThanhToan_HDCTLayout.setVerticalGroup(
            pnlSubThanhToan_HDCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubThanhToan_HDCTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHDCT)
                .addContainerGap())
        );

        pnlSubThanhToan.add(pnlSubThanhToan_HDCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 190, -1));

        pnlSubMenu.add(pnlSubThanhToan, "pnlSThanhToan");

        getContentPane().add(pnlSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 200, 310));

        pnlContent.setBackground(new java.awt.Color(211, 211, 211));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbpForm.setBackground(new java.awt.Color(204, 255, 102));
        pnlContent.add(tbpForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1080, 740));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 1070, 700));

        pnlFooter.setBackground(new java.awt.Color(102, 153, 255));
        pnlFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhóm 4");
        pnlFooter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, -1, 30));

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 1300, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadOpenForm();
    }//GEN-LAST:event_formWindowOpened

    private void pnlSubThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToanMouseExited
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_pnlSubThanhToanMouseExited

    private void pnlSubThanhToan_HDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDMouseEntered

    private void pnlSubThanhToan_HDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDMouseExited

    private void pnlSubThanhToan_HDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDCTMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDCTMouseEntered

    private void pnlSubThanhToan_HDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDCTMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDCTMouseExited

    private void pnlSubVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVeMouseExited
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_pnlSubVeMouseExited

    private void pnlSubVe_VeMBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_VeMBMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_VeMBMouseEntered

    private void pnlSubVe_VeMBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_VeMBMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_VeMBMouseExited

    private void pnlSubVe_HangVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_HangVeMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_HangVeMouseEntered

    private void pnlSubVe_HangVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_HangVeMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_HangVeMouseExited

    private void pnlSubVe_LoaiVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_LoaiVeMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_LoaiVeMouseEntered

    private void pnlSubVe_LoaiVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_LoaiVeMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_LoaiVeMouseExited

    private void pnlSubVe_DichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_DichVuMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_DichVuMouseEntered

    private void pnlSubVe_DichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubVe_DichVuMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubVe_DichVuMouseExited

    private void pnlSubChuyenBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBayMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSubChuyenBayMouseEntered

    private void pnlSubChuyenBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBayMouseExited
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_pnlSubChuyenBayMouseExited

    private void pnlSubChuyenBay_ChuyenBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_ChuyenBayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_ChuyenBayMouseEntered

    private void pnlSubChuyenBay_ChuyenBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_ChuyenBayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_ChuyenBayMouseExited

    private void pnlSubChuyenBay_TuyenBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_TuyenBayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_TuyenBayMouseEntered

    private void pnlSubChuyenBay_TuyenBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_TuyenBayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_TuyenBayMouseExited

    private void pnlSubChuyenBay_SanBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_SanBayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_SanBayMouseEntered

    private void pnlSubChuyenBay_SanBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_SanBayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_SanBayMouseExited

    private void pnlSubChuyenBay_MayBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_MayBayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_MayBayMouseEntered

    private void pnlSubChuyenBay_MayBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_MayBayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_MayBayMouseExited

    private void pnlSubChuyenBay_HangMayBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_HangMayBayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_HangMayBayMouseEntered

    private void pnlSubChuyenBay_HangMayBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubChuyenBay_HangMayBayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubChuyenBay_HangMayBayMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        changeIcon(1, btnClose, "src//Icon//closeMainGray.png");
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        changeIcon(2, btnClose, "src//Icon//closeMain.png");
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        minus();
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMinusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseEntered
        changeIcon(1, btnMinus, "src//Icon//minusMainGray.png");
    }//GEN-LAST:event_btnMinusMouseEntered

    private void btnMinusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseExited
        changeIcon(2, btnMinus, "src//Icon//minusMain.png");
    }//GEN-LAST:event_btnMinusMouseExited

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        tbpForm.removeAll();
        frmTrangChu tc = new frmTrangChu();
        tbpForm.addTab("", null, tc.getContentPane().getComponentAt(0, 0), null);
        lblUser.setText("NULL");
        lblChucVu.setText(null);
        frmLogin.tenDN = "";
        frmLogin.vt = "";
        login();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        changeIcon(1, btnLogout, "src//Icon//logoutGray.png");
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        changeIcon(2, btnLogout, "src//Icon//logout.png");
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        JOptionPane.showMessageDialog(this, "Đang phát triển!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        changeIcon(1, btnSetting, "src//Icon//settingGray.png");
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        changeIcon(2, btnSetting, "src//Icon//setting.png");
    }//GEN-LAST:event_btnSettingMouseExited

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        JOptionPane.showMessageDialog(this, "Đang phát triển!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseEntered
        changeIcon(1, btnAccount, "src//Icon//groupGray.png");
    }//GEN-LAST:event_btnAccountMouseEntered

    private void btnAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseExited
        changeIcon(2, btnAccount, "src//Icon//group.png");
    }//GEN-LAST:event_btnAccountMouseExited

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //menu();
        JOptionPane.showMessageDialog(this, "Đang phát triển!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        changeIcon(2, btnMenu, "src//Icon//menu.png");
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        changeIcon(1, btnMenu, "src//Icon//menuGray.png");
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        tbpForm.removeAll();
        frmTrangChu tc = new frmTrangChu();
        tbpForm.addTab("", null, tc.getContentPane().getComponentAt(0, 0), null);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseEntered
        hover(1, pnlTrangChu);
    }//GEN-LAST:event_btnTrangChuMouseEntered

    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseExited
        hover(2, pnlTrangChu);
    }//GEN-LAST:event_btnTrangChuMouseExited

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        if (!chucVu.isEmpty()) {
            tbpForm.removeAll();
            frmHanhKhach kh = new frmHanhKhach(chucVu);
            tbpForm.addTab("", null, kh.getContentPane().getComponentAt(0, 0), null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseEntered
        hover(1, pnlKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseEntered

    private void btnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseExited
        hover(2, pnlKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseExited

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if (!chucVu.isEmpty()) {
            tbpForm.removeAll();
            frmNhanVien nv = new frmNhanVien(chucVu);
            tbpForm.addTab("", null, nv.getContentPane().getComponentAt(0, 0), null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        hover(1, pnlNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        hover(2, pnlNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        if (!chucVu.isEmpty()) {
            showHideSubMenu(showHideSubMenu_ThanhToan, pnlSubThanhToan);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnThanhtoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhtoanMouseEntered
        hover(1, pnlThanhToan);
    }//GEN-LAST:event_btnThanhtoanMouseEntered

    private void btnThanhtoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhtoanMouseExited
        hover(2, pnlThanhToan);
    }//GEN-LAST:event_btnThanhtoanMouseExited

    private void btnQuanLyVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyVeActionPerformed
        if (!chucVu.isEmpty()) {
            showHideSubMenu(showHideSubMenu_Ve, pnlSubVe);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnQuanLyVeActionPerformed

    private void btnQuanLyVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyVeMouseEntered
        hover(1, pnlQuanLyVe);
    }//GEN-LAST:event_btnQuanLyVeMouseEntered

    private void btnQuanLyVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyVeMouseExited
        hover(2, pnlQuanLyVe);
    }//GEN-LAST:event_btnQuanLyVeMouseExited

    private void btnQuanLyChuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyChuyenBayActionPerformed
        if (!chucVu.isEmpty()) {
            showHideSubMenu(showHideSubMenu_ChuyenBay, pnlSubChuyenBay);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnQuanLyChuyenBayActionPerformed

    private void btnQuanLyChuyenBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyChuyenBayMouseEntered
        hover(1, pnlQuanLyChuyenBay);
    }//GEN-LAST:event_btnQuanLyChuyenBayMouseEntered

    private void btnQuanLyChuyenBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyChuyenBayMouseExited
        hover(2, pnlQuanLyChuyenBay);
    }//GEN-LAST:event_btnQuanLyChuyenBayMouseExited

    private void btnDoanhThuTheoQuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuTheoQuyActionPerformed
        if(!chucVu.isEmpty() && chucVu.equals("Trưởng phòng")){
            tbpForm.removeAll();
            frmDoanhThuTheoThang quy = new frmDoanhThuTheoThang();
            tbpForm.addTab("", null, quy.getContentPane().getComponentAt(0, 0), null);
        }else{
            JOptionPane.showMessageDialog(this, "Chỉ cấp quyền admin!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDoanhThuTheoQuyActionPerformed

    private void btnDoanhThuTheoQuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuTheoQuyMouseEntered
        hover(1, pnlQuanLyDoanhThu);
    }//GEN-LAST:event_btnDoanhThuTheoQuyMouseEntered

    private void btnDoanhThuTheoQuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuTheoQuyMouseExited
        hover(2, pnlQuanLyDoanhThu);
    }//GEN-LAST:event_btnDoanhThuTheoQuyMouseExited

    private void btnVeMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeMayBayActionPerformed
        tbpForm.removeAll();
        frmVeMayBay vemb = new frmVeMayBay(chucVu);
        tbpForm.addTab("", null, vemb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnVeMayBayActionPerformed

    private void btnVeMayBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMayBayMouseEntered
        hover(1, pnlSubVe_VeMB);
    }//GEN-LAST:event_btnVeMayBayMouseEntered

    private void btnHangVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangVeActionPerformed
        tbpForm.removeAll();
        frmHangVe hv = new frmHangVe(chucVu);
        tbpForm.addTab("", null, hv.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHangVeActionPerformed

    private void btnHangVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangVeMouseEntered
        hover(1, pnlSubVe_HangVe);
    }//GEN-LAST:event_btnHangVeMouseEntered

    private void btnHangVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangVeMouseExited
        hover(2, pnlSubVe_HangVe);
    }//GEN-LAST:event_btnHangVeMouseExited

    private void btnVeMayBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMayBayMouseExited
        hover(2, pnlSubVe_VeMB);
    }//GEN-LAST:event_btnVeMayBayMouseExited

    private void btnLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiVeActionPerformed
        tbpForm.removeAll();
        frmLoaiVe lv = new frmLoaiVe(chucVu);
        tbpForm.addTab("", null, lv.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnLoaiVeActionPerformed

    private void btnLoaiVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiVeMouseEntered
        hover(1, pnlSubVe_LoaiVe);
    }//GEN-LAST:event_btnLoaiVeMouseEntered

    private void btnLoaiVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiVeMouseExited
        hover(2, pnlSubVe_LoaiVe);
    }//GEN-LAST:event_btnLoaiVeMouseExited

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        tbpForm.removeAll();
        frmDichVu dv = new frmDichVu(chucVu);
        tbpForm.addTab("", null, dv.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnDichVuActionPerformed

    private void btnDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseEntered
        hover(1, pnlSubVe_DichVu);
    }//GEN-LAST:event_btnDichVuMouseEntered

    private void btnDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseExited
        hover(2, pnlSubVe_DichVu);
    }//GEN-LAST:event_btnDichVuMouseExited

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        tbpForm.removeAll();
        frmHoaDon hd = new frmHoaDon(chucVu);
        tbpForm.addTab("", null, hd.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseEntered
        hover(1, pnlSubThanhToan_HD);
    }//GEN-LAST:event_btnHoaDonMouseEntered

    private void btnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseExited
        hover(2, pnlSubThanhToan_HD);
    }//GEN-LAST:event_btnHoaDonMouseExited

    private void btnHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDCTActionPerformed
        tbpForm.removeAll();
        frmHoaDonChiTiet cthd = new frmHoaDonChiTiet(chucVu);
        tbpForm.addTab("", null, cthd.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHDCTActionPerformed

    private void btnHDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDCTMouseEntered
        hover(1, pnlSubThanhToan_HDCT);
    }//GEN-LAST:event_btnHDCTMouseEntered

    private void btnHDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDCTMouseExited
        hover(2, pnlSubThanhToan_HDCT);
    }//GEN-LAST:event_btnHDCTMouseExited

    private void btnChuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBayActionPerformed
        tbpForm.removeAll();
        frmChuyenBay cb = new frmChuyenBay(chucVu);
        tbpForm.addTab("", null, cb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnChuyenBayActionPerformed

    private void btnChuyenBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChuyenBayMouseEntered
        hover(1, pnlSubChuyenBay_ChuyenBay);
    }//GEN-LAST:event_btnChuyenBayMouseEntered

    private void btnChuyenBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChuyenBayMouseExited
        hover(2, pnlSubChuyenBay_ChuyenBay);
    }//GEN-LAST:event_btnChuyenBayMouseExited

    private void btnTuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuyenBayActionPerformed
        tbpForm.removeAll();
        frmTuyenBay tb = new frmTuyenBay(chucVu);
        tbpForm.addTab("", null, tb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnTuyenBayActionPerformed

    private void btnTuyenBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuyenBayMouseEntered
        hover(1, pnlSubChuyenBay_TuyenBay);
    }//GEN-LAST:event_btnTuyenBayMouseEntered

    private void btnTuyenBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuyenBayMouseExited
        hover(2, pnlSubChuyenBay_TuyenBay);
    }//GEN-LAST:event_btnTuyenBayMouseExited

    private void btnSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanBayActionPerformed
        tbpForm.removeAll();
        frmSanBay sb = new frmSanBay(chucVu);
        tbpForm.addTab("", null, sb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnSanBayActionPerformed

    private void btnSanBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanBayMouseEntered
        hover(1, pnlSubChuyenBay_SanBay);
    }//GEN-LAST:event_btnSanBayMouseEntered

    private void btnSanBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanBayMouseExited
        hover(2, pnlSubChuyenBay_SanBay);
    }//GEN-LAST:event_btnSanBayMouseExited

    private void btnMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayBayActionPerformed
        tbpForm.removeAll();
        frmMayBay mb = new frmMayBay(chucVu);
        tbpForm.addTab("", null, mb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnMayBayActionPerformed

    private void btnMayBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMayBayMouseEntered
        hover(1, pnlSubChuyenBay_MayBay);
    }//GEN-LAST:event_btnMayBayMouseEntered

    private void btnMayBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMayBayMouseExited
        hover(2, pnlSubChuyenBay_MayBay);
    }//GEN-LAST:event_btnMayBayMouseExited

    private void btnHangMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangMayBayActionPerformed
        tbpForm.removeAll();
        frmHangMayBay hmb = new frmHangMayBay(chucVu);
        tbpForm.addTab("", null, hmb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHangMayBayActionPerformed

    private void btnHangMayBayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangMayBayMouseEntered
        hover(1, pnlSubChuyenBay_HangMayBay);
    }//GEN-LAST:event_btnHangMayBayMouseEntered

    private void btnHangMayBayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangMayBayMouseExited
        hover(2, pnlSubChuyenBay_HangMayBay);
    }//GEN-LAST:event_btnHangMayBayMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnChuyenBay;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDichVu;
    private javax.swing.JButton btnDoanhThuTheoQuy;
    private javax.swing.JButton btnHDCT;
    private javax.swing.JButton btnHangMayBay;
    private javax.swing.JButton btnHangVe;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLoaiVe;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMayBay;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnQuanLyChuyenBay;
    private javax.swing.JButton btnQuanLyVe;
    private javax.swing.JButton btnSanBay;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnTuyenBay;
    private javax.swing.JButton btnVeMayBay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlQuanLyChuyenBay;
    private javax.swing.JPanel pnlQuanLyDoanhThu;
    private javax.swing.JPanel pnlQuanLyVe;
    private javax.swing.JPanel pnlSubChuyenBay;
    private javax.swing.JPanel pnlSubChuyenBay_ChuyenBay;
    private javax.swing.JPanel pnlSubChuyenBay_HangMayBay;
    private javax.swing.JPanel pnlSubChuyenBay_MayBay;
    private javax.swing.JPanel pnlSubChuyenBay_SanBay;
    private javax.swing.JPanel pnlSubChuyenBay_TuyenBay;
    private javax.swing.JPanel pnlSubMenu;
    private javax.swing.JPanel pnlSubThanhToan;
    private javax.swing.JPanel pnlSubThanhToan_HD;
    private javax.swing.JPanel pnlSubThanhToan_HDCT;
    private javax.swing.JPanel pnlSubVe;
    private javax.swing.JPanel pnlSubVe_DichVu;
    private javax.swing.JPanel pnlSubVe_HangVe;
    private javax.swing.JPanel pnlSubVe_LoaiVe;
    private javax.swing.JPanel pnlSubVe_VeMB;
    private javax.swing.JPanel pnlThanhToan;
    private javax.swing.JPanel pnlTrangChu;
    private javax.swing.JTabbedPane tbpForm;
    // End of variables declaration//GEN-END:variables
}
